### PR TITLE
Fix bug in snapshot-agent.go

### PR DESCRIPTION
**Pull request by silverwinter313**
Hi, we want to use your fork, but in code have bug in line.
When call UploadSnapshot, set zero bytes and after sent empty file in s3.
I make change and solved own problem. Can are you review fix?

### CODE REVIEW

**Review by Argelbargel — APPROVED** [review]

**Comment by Argelbargel** [comment]
Hi @silverwinter313 ,

thank you so very much! As i created this fork mainly to add some Things i missed in the original but had no real use case besides local storage, i had no was really to test my additions. Exactly the problem you found ist the one i saw when using the s3 storage but i did not have the time to Look into it...

**Comment by Argelbargel** [comment]
Oh, sorry just remembered that i'll have to tag a release for US to use the bugfix. Will doch that this week, promised!

**Comment by silverwinter313** [comment]
Thanks a lot, I wait new release with hot fix!

**Comment by Argelbargel** [comment]
HI @silverwinter313, Release 0.10.11 contains your bugfix. Binaries, Images and Helm-Charts should by uptodate by now...

**Pull request merged**
