### PR TITLE
fix(): update vulnerable modules

### PR DESCRIPTION
**Pull request by erlisb**
This PR contains the updated versions for the following go packages:

- go 1.21.0 -> 1.22.5
- github.com/hashicorp/vault/api                              v1.10.0 ->  v1.14.0
- github.com/hashicorp/vault/api/auth/approle        v0.5.0 -> v0.7.0
- github.com/hashicorp/vault/api/auth/aws              v0.5.0 -> v0.7.0
- github.com/hashicorp/vault/api/auth/azure           v0.5.0-> v0.6.0
- github.com/hashicorp/vault/api/auth/gcp              v0.5.0 -> v0.7.0
- github.com/hashicorp/vault/api/auth/kubernetes  v0.5.0 -> v0.7.0
- github.com/hashicorp/vault/api/auth/ldap             v0.5.0 -> v0.7.0
- github.com/hashicorp/vault/api/auth/userpass      v0.5.0 -> v0.7.0

 
Thanks.

### CODE REVIEW

**Comment by erlisb** [comment]
Hi @Argelbargel , during our tests we found a lot of vulnerable go packages, that blocks our work to deploy this in a prod environment.
Please, check this PR and let us know.
Thanks.

**Comment by Argelbargel** [comment]
HI @erlisb,

your pr contains a binary, which i do not trust ;-)

So instead of approving this request i updated the dependencies myself. Hope that works for you, too.

**Comment by erlisb** [comment]
Hi @Argelbargel, that's coming from my local tests, which I forgot to exclude.
Thanks for your fix.

**Comment by erlisb** [comment]
Hi @Argelbargel,

I gave it another scan with trivy and it shows the following vulnerabilities:

> $ trivy i ghcr.io/argelbargel/vault-raft-snapshot-agent:v0.10.15

image
image
image
image

Any ideas ?

Thnx.

**Comment by glisav** [comment]
Hi @Argelbargel 

Could please update the Go version also in go.mod file, because it is not updated:

image

Thank you!

**Comment by Argelbargel** [comment]
Hi @glisav,

oh, sorry, i thought go get -u would update that too. 

Now everything should be uptodate...

**Pull request closed without merging**
